### ISSUE TITLE
Allocating randomly participants and mentors to groups

### ISSUE THREAD

**Issue by Vardane** [ygingras/mp-84-atelier#1]

**Comment by Vardane** [comment]
[groupes.txt](https://github.com/ygingras/mp-84-atelier/files/6096255/groupes.txt)
[groupes_12p_3m.txt](https://github.com/ygingras/mp-84-atelier/files/6096256/groupes_12p_3m.txt)
[groupes_23p_7m.txt](https://github.com/ygingras/mp-84-atelier/files/6096257/groupes_23p_7m.txt)
[members.txt](https://github.com/ygingras/mp-84-atelier/files/6096258/members.txt)
[members_12p_3m.txt](https://github.com/ygingras/mp-84-atelier/files/6096259/members_12p_3m.txt)
[members_23p_7m.txt](https://github.com/ygingras/mp-84-atelier/files/6096260/members_23p_7m.txt)

**Comment by Vardane** [comment]
Sample of input and output files, varying the number of participants and mentors for test purposes.

**Comment by ygingras** [comment]
Excellent!  Je pensais appeler les sales: atelier-G à atelier-J (aucune association de mérite présumé avec ces lettres).  Le message d’assignation pourrait donc inclure le cannal.  Par exemple:

    Pour la prochaine période d'exercices, dirigez vous vers les salons suivant.  Vous aurez ainsi la chance de travailler avec des mentors en plus petit groupes.
    #atelier-G: bob, marc, maurice🐍
    #atelier-H: martin, Mélanie, Édith🐍, Jules🐍

**Comment by Vardane** [comment]
Parfait, je vais ajuster cela!

**Comment by ygingras** [comment]
Tu peux m'envoyer une PR avec le(s) scripte(s).  J'ai mis l'autre dans `admin`.

**Comment by Vardane** [comment]
J'avais fait une PR sur une nouvelle branche: Allocating-Participants-and-Mentors
Préfères tu que je la supprime et que je refasse une PR sur la branche Main?

**Comment by ygingras** [comment]
Tu peux la modifier pour la diriger vers main, tu ne devais pas avoir besoin de la supprimer.  Les changements sont assez simple qu'on n'a pas besoin d'une nouvelle branche pour ca.  :-)

**Comment by Vardane** [comment]
[groupes.txt](https://github.com/ygingras/mp-84-atelier/files/6096359/groupes.txt)

**Comment by Vardane** [comment]
Ajusté comme discuté. Je t'envoie le fichier du code par PR sur Main sous peu.
